name: "Integrate"

on:
  workflow_call:
    inputs:
      phpVersion:
        description: 'Version of PHP to be used'
        required: false
        type: string
        default: '8.2'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.phpVersion }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl

      - uses: ramsey/composer-install@v2

      - name: Create new Jigsaw Build
        run: composer run build:production
